#!/usr/bin/env bash
# build-amd64-experimental.sh — produce an amd64 image with the rp shadow-FS
# overlay applied, for verifying rp's FUSE bits work on x86 via Docker.
#
# SCOPE (deliberately narrow — this is a smoke-test tool, not a production
# path):
#   * Builds linux/amd64 only, via `docker buildx`.
#   * Includes rp-fuse + rp-init.sh + the overlay's fuse3/user/mountpoint
#     setup. Does NOT install any agent profile (no claude/opencode), no
#     /etc/rp/instructions compose, no caller-ownership probe.
#   * Lands the result in the local docker daemon. No push, no registry.
#
# Usage:
#   scripts/build-amd64-experimental.sh <base-image>
#
# Example:
#   scripts/build-amd64-experimental.sh debian:bookworm-slim
#   docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse \
#       -v /tmp/probe-ws:/workspace-real \
#       rp-amd64-experiment:debian-bookworm-slim /usr/local/bin/rp-init.sh
#
# Requires: Docker Desktop with buildx (default on recent installs). The
# rp-fuse cross-compile + the user image work both run under buildx's
# linux/amd64 emulation — slow on Apple Silicon but doesn't need a real
# amd64 host.

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "usage: build-amd64-experimental.sh <base-image>" >&2
    echo "" >&2
    echo "Example: build-amd64-experimental.sh debian:bookworm-slim" >&2
    exit 2
fi

BASE=$1
REPO_DIR=$(cd "$(dirname "$0")/.." && pwd)

if ! docker buildx version >/dev/null 2>&1; then
    echo "build-amd64-experimental: docker buildx not available; install Docker Desktop" >&2
    exit 1
fi

# Derive a filesystem-safe slug from the base image ref. mcr.../universal:linux
# → mcr-universal-linux. Used as a tag suffix so multiple bases coexist.
SLUG=$(echo "$BASE" \
    | tr '/' '-' \
    | tr ':' '-' \
    | tr '.' '-' \
    | sed 's/[^a-zA-Z0-9_-]//g' \
    | sed 's/^mcr-microsoft-com-//' \
    | sed 's/-devcontainers//')

BASE_TAG="rp-base-amd64:experiment"
OUT_TAG="rp-amd64-experiment:${SLUG}"

# --- Stage 1: build rp-base for amd64 ----------------------------------
echo ">> [1/2] Building $BASE_TAG (linux/amd64) via buildx ..." >&2
docker buildx build \
    --platform linux/amd64 \
    -f "$REPO_DIR/Dockerfile.base" \
    -t "$BASE_TAG" \
    --load \
    "$REPO_DIR"

# --- Stage 2: generate minimal overlay Dockerfile + build it ------------
OVERLAY_CTX=$(mktemp -d -t rp-amd64-overlay.XXXXXX)
trap "rm -rf $OVERLAY_CTX" EXIT

cat > "$OVERLAY_CTX/Dockerfile" <<EOF
# Auto-generated by build-amd64-experimental.sh. Do not edit.
# Mirrors the runtime overlay produced by scripts/build-project-image.sh
# but stripped of agent-profile bits (no install.sh, no instructions, no
# settings files). Used to smoke-test the FUSE shadow stack on amd64.
FROM $BASE
USER root
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends fuse3 \\
    && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/^#user_allow_other/user_allow_other/' /etc/fuse.conf 2>/dev/null \\
    || echo 'user_allow_other' >> /etc/fuse.conf

# Default container user — fresh coder, no sudo.
RUN id -u coder >/dev/null 2>&1 || useradd -m -s /bin/bash coder
RUN test "\$(id -u coder)" -ne 0 \\
    || (echo "rp-amd64-experiment: user 'coder' is root, refusing" >&2; exit 1)
RUN ! grep -rqE "(^|[[:space:]])coder([[:space:]]|\$)" /etc/sudoers /etc/sudoers.d/ 2>/dev/null \\
    || (echo "rp-amd64-experiment: user 'coder' has a sudoers entry, refusing" >&2; exit 1)

RUN mkdir -p /var/lib/rp/shadow /var/lib/rp/backing /workspace /workspace-real /usr/local/lib/rp \\
    && chmod 0700 /var/lib/rp \\
    && chown root:root /var/lib/rp /var/lib/rp/shadow /var/lib/rp/backing

# Pull rp-fuse + init script from the amd64 rp-base we just built.
COPY --from=$BASE_TAG /usr/local/bin/rp-fuse /usr/local/bin/rp-fuse
COPY --from=$BASE_TAG /usr/local/bin/rp-init.sh /usr/local/bin/rp-init.sh
COPY --from=$BASE_TAG /etc/rp/instructions/00-container.md /etc/rp/instructions/00-container.md
RUN chmod 0755 /usr/local/bin/rp-fuse /usr/local/bin/rp-init.sh

WORKDIR /workspace
USER coder
EOF

if [ "${RP_DEBUG:-}" = "1" ]; then
    echo ">> generated overlay Dockerfile ↓↓↓" >&2
    sed 's/^/   /' "$OVERLAY_CTX/Dockerfile" >&2
    echo ">> ↑↑↑" >&2
fi

echo ">> [2/2] Building $OUT_TAG (FROM $BASE) via buildx ..." >&2
docker buildx build \
    --platform linux/amd64 \
    -f "$OVERLAY_CTX/Dockerfile" \
    -t "$OUT_TAG" \
    --load \
    "$OVERLAY_CTX"

cat >&2 <<MSG

----------------------------------------------------------------------
Built: $OUT_TAG (linux/amd64), in the local docker daemon.

Smoke-test it with:

  mkdir -p /tmp/rp-amd64-probe
  docker run --rm -it \\
      --cap-add SYS_ADMIN \\
      --device /dev/fuse \\
      -v /tmp/rp-amd64-probe:/workspace-real \\
      $OUT_TAG \\
      /usr/local/bin/rp-init.sh

In another shell:
  docker exec -it -u coder <container-id> bash

Inside, /workspace is the FUSE-mediated mount. /var/lib/rp is the
root-only shadow store. .rp/shadow rules in /workspace-real are honored.
This image does NOT have any agent installed — it's a FUSE smoke test.
----------------------------------------------------------------------
MSG
